// swift-tools-version:6.0
//
// astrid-core for the Apple apps: the Rust core (https://github.com/Graceful-Tools/astrid-core)
// as a prebuilt XCFramework, its generated bindings, and the small Swift layer the apps call.
//
// The framework comes from one of two places:
//
// - **A local build**, when `AstridCoreFFI.xcframework` sits beside this file —
//   `scripts/core/build-xcframework.sh` puts it there (it is gitignored). This is the inner loop,
//   and the way to build against a local astrid-core checkout.
// - **A released zip**, pinned below by URL and checksum, otherwise. That is what Xcode Cloud
//   builds, because it has no Rust toolchain; `scripts/core/release-xcframework.sh` publishes one
//   and rewrites the two constants.
import Foundation
import PackageDescription

let releasedURL = "https://github.com/Graceful-Tools/astrid-ios/releases/download/core-unreleased/AstridCoreFFI.xcframework.zip"
let releasedChecksum = "0000000000000000000000000000000000000000000000000000000000000000"

let localFramework = Context.packageDirectory + "/AstridCoreFFI.xcframework"
let framework: Target = FileManager.default.fileExists(atPath: localFramework)
    ? .binaryTarget(name: "AstridCoreFFI", path: "AstridCoreFFI.xcframework")
    : .binaryTarget(name: "AstridCoreFFI", url: releasedURL, checksum: releasedChecksum)

let package = Package(
    name: "AstridCore",
    platforms: [.iOS(.v18), .macOS(.v14)],
    products: [
        .library(name: "AstridCore", targets: ["AstridCore"]),
    ],
    targets: [
        framework,
        // Generated by uniffi-bindgen — never edited by hand.
        .target(
            name: "AstridCoreBindings",
            dependencies: ["AstridCoreFFI"],
            linkerSettings: [
                // What the Rust side links against: TLS and proxy settings for the HTTP client.
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        .target(name: "AstridCore", dependencies: ["AstridCoreBindings"]),
        .testTarget(name: "AstridCoreTests", dependencies: ["AstridCore"]),
    ],
    // The apps compile in Swift 5 mode, and so does what UniFFI generates.
    swiftLanguageModes: [.v5]
)
