import Foundation

/**
 * OAuth Manager for iOS
 *
 * Handles OAuth 2.0 client credentials flow for the iOS app.
 * Automatically manages token lifecycle (generation, refresh, expiration).
 */
class OAuthManager {
    static let shared = OAuthManager()

    private enum CacheKey {
        static let legacyToken = "oauth_token_cache"
        static let expiresAt = "oauth_token_expires_at"
    }

    // OAuth Configuration
    private struct OAuthConfig {
        // OAuth Client Credentials (generated by setup-ios-oauth script)
        static let clientId = "astrid_client_be2300aa9f034889e836ba0efc9c5e8d"
        static let clientSecret: String = {
            // Load from keychain (stored during first run)
            if let secret = KeychainService.shared.getOAuthClientSecret() {
                return secret
            }
            // Fallback - should be set during app first run
            return ""
        }()
        static let scopes = [
            "tasks:read",
            "tasks:write",
            "tasks:delete",
            "lists:read",
            "lists:write",
            "lists:delete",
            "lists:manage_members",
            "comments:read",
            "comments:write",
            "comments:delete",
            "attachments:read",
            "attachments:write",
            "attachments:delete",
            "user:read",
            "user:write",
            "public:read",
            "public:write"
        ]
    }

    // Token state
    private var accessToken: String?
    private var tokenExpiresAt: Date?
    private var isRefreshing = false
    private var refreshCallbacks: [(Result<String, Error>) -> Void] = []

    // Configuration
    private let baseURL: URL
    private let session: URLSession

    private init() {
        self.baseURL = URL(string: Constants.API.baseURL)!

        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = Constants.API.timeout
        self.session = URLSession(configuration: configuration)

        // Try to load cached token
        loadCachedToken()
    }

    // MARK: - Public API

    /**
     * Get a valid access token
     * Automatically refreshes if expired or about to expire
     */
    func getAccessToken() async throws -> String {
        // Check if we have a valid cached token
        if let token = accessToken,
           let expiresAt = tokenExpiresAt,
           expiresAt > Date().addingTimeInterval(60) { // 1 min buffer
            return token
        }

        // Prevent concurrent refresh requests
        if isRefreshing {
            return try await waitForRefresh()
        }

        // Refresh the token
        return try await refreshAccessToken()
    }

    /**
     * Configure OAuth credentials
     * Should be called after user signs in for the first time
     */
    func configure(clientSecret: String) {
        KeychainService.shared.saveOAuthClientSecret(clientSecret)
    }

    /**
     * Clear all OAuth credentials
     * Call on logout
     */
    func clearCredentials() {
        accessToken = nil
        tokenExpiresAt = nil
        KeychainService.shared.deleteOAuthClientSecret()
        try? KeychainService.shared.deleteOAuthAccessToken()
        clearCachedToken()
    }

    // MARK: - Token Management

    private func refreshAccessToken() async throws -> String {
        isRefreshing = true
        defer { isRefreshing = false }

        print("🔐 [OAuthManager] Refreshing access token...")

        // Check if we have credentials
        let clientSecret = OAuthConfig.clientSecret
        if clientSecret.isEmpty {
            print("❌ [OAuthManager] No client secret found in Keychain!")
            print("⚠️ [OAuthManager] OAuth secret must be configured. Call OAuthManager.shared.configure(clientSecret:)")
            throw OAuthError.noCredentials
        }

        print("✅ [OAuthManager] Client secret found, requesting token...")

        let endpoint = baseURL.appendingPathComponent("/api/v1/oauth/token")
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")

        // Build request body
        var components = URLComponents()
        components.queryItems = [
            URLQueryItem(name: "grant_type", value: "client_credentials"),
            URLQueryItem(name: "client_id", value: OAuthConfig.clientId),
            URLQueryItem(name: "client_secret", value: clientSecret),
            URLQueryItem(name: "scope", value: OAuthConfig.scopes.joined(separator: " "))
        ]
        request.httpBody = components.query?.data(using: .utf8)

        do {
            let (data, response) = try await session.data(for: request)

            guard let httpResponse = response as? HTTPURLResponse else {
                throw OAuthError.invalidResponse
            }

            if httpResponse.statusCode == 401 {
                print("❌ [OAuthManager] Invalid credentials")
                throw OAuthError.invalidCredentials
            }

            guard httpResponse.statusCode == 200 else {
                let errorMsg = String(data: data, encoding: .utf8) ?? "Unknown error"
                print("❌ [OAuthManager] Token request failed: \(errorMsg)")
                throw OAuthError.requestFailed(httpResponse.statusCode)
            }

            let tokenResponse = try JSONDecoder().decode(OAuthTokenResponse.self, from: data)

            // Cache the token
            accessToken = tokenResponse.accessToken
            tokenExpiresAt = Date().addingTimeInterval(TimeInterval(tokenResponse.expiresIn))

            // Persist token material in Keychain; UserDefaults contains only expiry metadata.
            try cacheToken(token: tokenResponse.accessToken, expiresAt: tokenExpiresAt!)

            print("✅ [OAuthManager] Access token obtained (expires in \(tokenResponse.expiresIn)s)")

            // Notify any waiting callers
            notifyRefreshCallbacks(.success(tokenResponse.accessToken))

            return tokenResponse.accessToken

        } catch {
            print("❌ [OAuthManager] Token refresh failed: \(error)")
            notifyRefreshCallbacks(.failure(error))
            throw error
        }
    }

    private func waitForRefresh() async throws -> String {
        return try await withCheckedThrowingContinuation { continuation in
            refreshCallbacks.append { result in
                continuation.resume(with: result)
            }
        }
    }

    private func notifyRefreshCallbacks(_ result: Result<String, Error>) {
        let callbacks = refreshCallbacks
        refreshCallbacks.removeAll()

        for callback in callbacks {
            callback(result)
        }
    }

    // MARK: - Token Caching

    private func cacheToken(token: String, expiresAt: Date) throws {
        try KeychainService.shared.saveOAuthAccessToken(token)
        UserDefaults.standard.set(expiresAt.timeIntervalSince1970, forKey: CacheKey.expiresAt)
        UserDefaults.standard.removeObject(forKey: CacheKey.legacyToken)
    }

    private func loadCachedToken() {
        // One-time migration for builds that stored token material in UserDefaults.
        if let data = UserDefaults.standard.data(forKey: CacheKey.legacyToken),
           let cacheData = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let legacyToken = cacheData["token"] as? String,
           let legacyExpiry = cacheData["expiresAt"] as? TimeInterval,
           legacyExpiry > Date().timeIntervalSince1970 {
            try? KeychainService.shared.saveOAuthAccessToken(legacyToken)
            UserDefaults.standard.set(legacyExpiry, forKey: CacheKey.expiresAt)
        }
        UserDefaults.standard.removeObject(forKey: CacheKey.legacyToken)

        guard let token = try? KeychainService.shared.getOAuthAccessToken() else { return }
        let expiresAtTimestamp = UserDefaults.standard.double(forKey: CacheKey.expiresAt)
        guard expiresAtTimestamp > 0 else {
            try? KeychainService.shared.deleteOAuthAccessToken()
            return
        }

        let expiresAt = Date(timeIntervalSince1970: expiresAtTimestamp)

        // Only use cached token if still valid
        if expiresAt > Date() {
            accessToken = token
            tokenExpiresAt = expiresAt
            print("✅ [OAuthManager] Loaded cached token (expires at \(expiresAt))")
        } else {
            print("⏰ [OAuthManager] Cached token expired, will refresh on next request")
            clearCachedToken()
        }
    }

    private func clearCachedToken() {
        try? KeychainService.shared.deleteOAuthAccessToken()
        UserDefaults.standard.removeObject(forKey: CacheKey.expiresAt)
        UserDefaults.standard.removeObject(forKey: CacheKey.legacyToken)
    }
}

// MARK: - Response Models

struct OAuthTokenResponse: Codable {
    let accessToken: String
    let tokenType: String
    let expiresIn: Int
    let scope: String

    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case scope
    }
}

// MARK: - Errors

enum OAuthError: LocalizedError {
    case noCredentials
    case invalidCredentials
    case invalidResponse
    case requestFailed(Int)

    var errorDescription: String? {
        switch self {
        case .noCredentials:
            return "OAuth credentials not configured. Please sign in again."
        case .invalidCredentials:
            return "Invalid OAuth credentials. Please sign in again."
        case .invalidResponse:
            return "Invalid response from authentication server"
        case .requestFailed(let code):
            return "Authentication failed with code: \(code)"
        }
    }
}
